### PR TITLE
Add Ueno as a maintainer and set codeowners

### PR DESCRIPTION
**Pull request by lukehinds**
codeowners also set, which allows for better branch protections

Resolves: #250

Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Review by mpeters — APPROVED** [review]
lgtm

**Review by lkatalin — APPROVED** [review]

**Comment by lkatalin** [comment]
This looks like one of those cases where an unrelated clippy error is causing the CI to fail. I can put in a fix for it pretty quick, I think.

**Comment by lukehinds** [comment]
> This looks like one of those cases where an unrelated clippy error is causing the CI to fail. I can put in a fix for it pretty quick, I think.

got for it

**Comment by lkatalin** [comment]
@lukehinds You're good to rebase now and it should fix CI.

**Pull request merged**
