### PR TITLE
Fix line split in secure mount and notify

### PR DESCRIPTION
**Pull request by lukehinds**
Currently the code splits the mount command line returns
incorrectly. This results in a non match which means a new
mount is created everytime, instead of using an existing mount.

This results in many mounts being present on the system, every
time the agent is restarted.

This is due to the split element being a back slash `\` whereas
it should be a whitespace `' '`

There is also no feedback provided to the user when an existing
mount is used. This information should be provided to the user.

Resolves: #83

### CODE REVIEW

**Comment by lukehinds** [comment]
Apologies, there is an additional change I omitted to mention which is making the function public. I can reverse this change or put into a new patch, but this is required so that we can actually call the function, so I am happy to have it in this patch if this does not bother others.

**Comment by frozencemetery** [comment]
How does this interact with #82, given that's moving the code around?  Seems like we should wait until that's merged to do this, right?

**Comment by lukehinds** [comment]
> How does this interact with #82, given that's moving the code around? Seems like we should wait until that's merged to do this, right?

Sorry, yes I should have marked this as depending on the other patch landing first.

**Comment by lukehinds** [comment]
@frozencemetery we are good to merge this one now.

Next I will work on landing the tpm2 patch and then we start to call the various functions and connect the code together. I think first we will get the TPM operations working, and then look at the request handlers and post interface in the agent.

**Pull request merged**
