### PR TITLE
secure_mount: fix tmpfs creation for secure mount point

### PR DESCRIPTION
**Pull request by THS-on**
Using `cmd_exec::run` errors with:
```
 INFO  keylime_agent::quotes_handler  > GET integrity quote returning 200 response
 INFO  keylime_agent::keys_handler    > Received vkey
 INFO  keylime_agent::keys_handler    > HMAC check passed
 INFO  keylime_agent::keys_handler    > Successfully derived symmetric payload decryption key
 INFO  keylime_agent                  > Successfully decrypted payload
 INFO  keylime_agent::secure_mount    > secure storage location /tmp/secure not mounted.
 INFO  keylime_agent::secure_mount    > Directory "/tmp/secure" created.
 INFO  keylime_agent::secure_mount    > Mounting secure storage location /tmp/secure on tmpfs.
 INFO  keylime_agent::common          > Changed file /tmp/secure owner to root.
 INFO  keylime_agent::secure_mount    > Changed path /tmp/secure owner to root.
Error: Other("cannot get execution status code for Error type IO error: No such file or directory (os error 2)")
```
We now call mount directly using `Command` instead of the retry abstraction. `cmd_exec` is now unused and can be removed because we interact with the TPM directly using the tss bindings.

The `WORK_DIR` is changed to `/var/lib/keylime` to be consistent with the Python agent.

### CODE REVIEW

**Comment by THS-on** [comment]
I see that #286 should also fix this issue, but I think that we don't need `cmd_exec` just for the calls to `mount`.

**Comment by ueno** [comment]
Yes, and this looks much cleaner; maybe we could also remove `cmd_exec.rs`, given the agent doesn't rely on tpm2-tools?

**Comment by THS-on** [comment]
@ueno Yeah this PR also removes `cmd_exec.rs`.

**Review by ueno — APPROVED** [review]

**Review by lkatalin — APPROVED** [review]
@THS-on This change was on my to-do list. Thank you so much.

**Comment by lkatalin** [comment]
Looks good and related to #220

**Pull request merged**
