### PR TITLE
quotes_handler: Rewind measured boot log file

### PR DESCRIPTION
**Pull request by ansasaki**
Rewind the file before reading its content.

Fixes: #383 

Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

### CODE REVIEW

**Comment by THS-on** [comment]
The measured boot log should never change after boot, so we just could keep it in memory instead of reading it again.

**Comment by maugustosilva** [comment]
I can confirm this single line change indeed fixes the problem. LGTM

**Comment by ansasaki** [comment]
> The measured boot log should never change after boot, so we just could keep it in memory instead of reading it again.

This is probably the best solution. I'll make the changes towards this.

**Comment by lukehinds** [comment]
Just a nit, can the unwrap be error handled instead (I figure rewind is an Option or Result). Perhaps even .except with a meaningful error message.

**Comment by ansasaki** [comment]
After some discussion, it was decided to revert the change to simply add a rewind. There is no clear benefit on holding several KB of data on memory all the time to avoid rewinding and re-reading the file which is on a memory-based file system.

**Comment by ansasaki** [comment]
@lkatalin @lukehinds @ashcrow Could you review/approve this?

**Review by lkatalin — APPROVED** [review]

**Pull request merged**
