### PR TITLE
cargo: Bump serde to version 1.0.188

### PR DESCRIPTION
**Pull request by ansasaki**
Supersedes #631

### CODE REVIEW

**Comment by aplanas** [comment]
What can be the timeout from the Rust / Fedora test?

**Comment by ansasaki** [comment]
> What can be the timeout from the Rust / Fedora test?

That is a tarpaulin (test coverage measurement) issue dealing with parallel processing. The last time I investigated it , it was related with this open issue: https://github.com/xd009642/tarpaulin/issues/971. It happens from time to time and it is annoying. Most of the time a re-run makes the test to pass.

Maybe we could try to use the option they recommend there `--engine llvm` and see if it improves the situation.

**Comment by aplanas** [comment]
There is also this related with tarpaulin in testing-farm:fedora-37:

```
:: [ 09:30:13 ] :: [  BEGIN   ] :: Running 'cargo tarpaulin -v --target-dir target/tarpaulin --workspace --exclude-files 'target/*' --ignore-panics --ignore-tests --out Xml --out Html --all-features'

error: unexpected argument '-v' found
```

Seems that the cli changed, maybe after an update

**Comment by aplanas** [comment]
Ah ... related: https://github.com/xd009642/tarpaulin/pull/1389

**Comment by ansasaki** [comment]
> There is also this related with tarpaulin in testing-farm:fedora-37:
> 
> ```
> :: [ 09:30:13 ] :: [  BEGIN   ] :: Running 'cargo tarpaulin -v --target-dir target/tarpaulin --workspace --exclude-files 'target/*' --ignore-panics --ignore-tests --out Xml --out Html --all-features'
> 
> error: unexpected argument '-v' found
> ```
> 
> Seems that the cli changed, maybe after an update

Yes, we are aware of this, thank you for checking anyway!

They accidentally dropped the `-v` option on the latest release. The option was restored upstream, but not released yet.
See: https://github.com/xd009642/tarpaulin/pull/1389

**Comment by ansasaki** [comment]
> > There is also this related with tarpaulin in testing-farm:fedora-37:
> > ```
> > :: [ 09:30:13 ] :: [  BEGIN   ] :: Running 'cargo tarpaulin -v --target-dir target/tarpaulin --workspace --exclude-files 'target/*' --ignore-panics --ignore-tests --out Xml --out Html --all-features'
> > 
> > error: unexpected argument '-v' found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems that the cli changed, maybe after an update
> 
> Yes, we are aware of this, thank you for checking anyway!
> 
> They accidentally dropped the `-v` option on the latest release. The option was restored upstream, but not released yet. See: [xd009642/tarpaulin#1389](https://github.com/xd009642/tarpaulin/pull/1389)

BTW, I think I'll fix this (by using the long option) and also try using the `--engine llvm` in a separate PR.

**Comment by ansasaki** [comment]
Opened https://github.com/keylime/rust-keylime/pull/663

**Pull request merged**
