### PR TITLE
e2e tests: Fix test name

### PR DESCRIPTION
**Pull request by kkaarreell**
Signed-off-by: Karel Srot <ksrot@redhat.com>

### CODE REVIEW

**Comment by kkaarreell** [comment]
Newly enabled test will be failing due to regression
https://github.com/keylime/keylime/issues/1306
introduced in https://github.com/keylime/keylime/pull/1272

**Comment by kkaarreell** [comment]
That test abort could be some packaging/repository issue on F37

**Comment by THS-on** [comment]
@kkaarreell it fails with:
```
  file /usr/share/doc/tpm2-tss/CHANGELOG.md from install of tpm2-tss-3.2.2-1.fc37.i686 conflicts with file from package tpm2-tss-3.2.1-1.fc37.x86_64
```

This has definitely nothing to do with this change.

**Comment by kkaarreell** [comment]
It does not, for some reason it doesn't find newer  x86_64 RPM. @Koncpa Could you Pls check it on Monday?

**Comment by Koncpa** [comment]
@kkaarreell Sure

**Pull request merged**
