### PR TITLE
Run payload script from a shell

### PR DESCRIPTION
**Pull request by ueno**
Otherwise, it throws "Exec format error (os error 8)" unless it is a
native binary.  Also simplified the logic to set executable bit of the
script.

Signed-off-by: Daiki Ueno <dueno@redhat.com>

### CODE REVIEW

**Review by ashcrow — COMMENTED** [review]
Changes look good to me. One question: will `test-output` file be left on the filesystem as a test side effect? If so, should we remove it or maybe add it to .gitignore?

**Comment by ueno** [comment]
The file should be automatically removed, because `run` changes the directory to the tempdir before running the script (so `test-output` should be created inside tempdir).

**Comment by lkatalin** [comment]
I like these changes also.

**Review by lkatalin — APPROVED** [review]

**Comment by lkatalin** [comment]
@ashcrow I'll merge this since your question was addressed.

**Pull request merged**
