### PR TITLE
Apache license header to source files

### LINKED ISSUE #111: Apache 2.0 licensing headers needed

### PR DESCRIPTION
**Pull request by ashcrow**
- Add ASLv2 SPDX header to source files
- Add `license-header.tpl`
- Add commented out config for `rustfmt` to check for license headers in the future

Resolves #111

### CODE REVIEW

**Comment by ashcrow** [comment]
@lkatalin I'm happy to wait on https://github.com/keylime/rust-keylime/pull/158 to merge and rebase this on top if that would be helpful.

**Comment by lkatalin** [comment]
> @lkatalin I'm happy to wait on #158 to merge and rebase this on top if that would be helpful.

Thanks! I'm not sure how much more review that one will need, so I am okay with this merging first. Then I can update headers in my PR.

**Comment by lkatalin** [comment]
This looks good. Having the `license_template_path` in `rustfmt.toml` in the future will make it so that `[cargo fmt --all -- --check](https://github.com/keylime/rust-keylime/blob/master/.github/workflows/rust.yml#L19)` will catch any files that don't have the header, is that right?

**Comment by ashcrow** [comment]
That's correct!

**Review by lkatalin — APPROVED** [review]

**Review by lukehinds — APPROVED** [review]

**Comment by ashcrow** [comment]
2 :heavy_check_mark:'s ... merging.

**Pull request merged**
