### PR TITLE
Retain the main loop running after payload execution

### PR DESCRIPTION
**Pull request by ueno**
Fixes: #247

Still a draft as I haven't checked every error case that we can ignore.

### CODE REVIEW

**Comment by lkatalin** [comment]
This is much better. Thanks for making this change.

**Comment by lkatalin** [comment]
@ueno Would you be open to merging this version? I think it may help with #262 (other fixes are also needed, which I am working on).

**Comment by ueno** [comment]
@lkatalin sure, just rebased against master.

**Review by lkatalin — APPROVED** [review]

**Comment by lkatalin** [comment]
> @lkatalin sure, just rebased against master.

@ueno Thanks! GHA was down for a bit and it looks like the tests got stuck; I tried to re-trigger it from this end but it hasn't helped, so if you get a chance do you mind re-pushing to see if that fixes it?

**Comment by ueno** [comment]
Thanks for the review.

**Pull request merged**
