### PR TITLE
Add agent and faked_measured_boot_log tests context

### PR DESCRIPTION
**Pull request by kkaarreell**
These context are to be used for proper test case filtering.
Current upstream plan installs modified Rust agent which
reads faked measured boot log, enabling measured boot testing
on systems with runtime swtpm emulation.
Distribution RPMs are not modified this way and undefined context
faked_measured_boot_log gives as a way how to avoid running measured
boot test that would fail.

Signed-off-by: Karel Srot <ksrot@redhat.com>

### CODE REVIEW

**Comment by kkaarreell** [comment]
Rust / Fedora tests failure should not be related to this commit. Can anyone please take a look if this is a know issue? Thank you.

**Comment by lkatalin** [comment]
> Rust / Fedora tests failure should not be related to this commit. Can anyone please take a look if this is a know issue? Thank you.

#443 should help

**Comment by kkaarreell** [comment]
Hello @ueno @lkatalin @lukehinds , could you please merge this PR? It only sets test metadata and CI failure is clearly unrelated. We need improved test filtering for ongoing RHEL testing. That being said, I will merge https://github.com/RedHat-SP-Security/keylime-tests/pull/193 either way, but not having PR#442 merged would mean that `functional/measured-boot-swtpm-sanity` test won't be run for the Rust agent in upstream Packit CI.

**Comment by lukehinds** [comment]
I honestly don't know enough about packit to review, is this for downstream testing? if so, I can merge it as it's not going to have any impact here (not to say its wrong, but I don't believe we use packit upstream / here)?

**Review by lukehinds — APPROVED** [review]

**Review by lkatalin — APPROVED** [review]

**Comment by lkatalin** [comment]
I'm fine merging after it's rebased on #443 (which still needs to be merged)

**Comment by lkatalin** [comment]
> I'm fine merging after it's rebased on #443 (which still needs to be merged)

@kkaarreell I just merged #443 . If you are okay rebasing, I can merge this one asap.

**Comment by lkatalin** [comment]
> > I'm fine merging after it's rebased on #443 (which still needs to be merged)
> 
> @kkaarreell I just merged #443 . If you are okay rebasing, I can merge this one asap.

Actually, maybe it will just let me bring in the changes through here.

**Pull request merged**
