### PR TITLE
Use cpu_endian to check local endianness

### PR DESCRIPTION
**Pull request by sarroutbi**
Resolves: #283

### CODE REVIEW

**Comment by aplanas** [comment]
> If anybody can help with this, I am grateful. Otherwise, I will keep the PR as it is right now

You need to add a bound to "T". IIUC "T" will always be "u32", "u16" or "u8". I that case maybe you can use something like this: https://users.rust-lang.org/t/generic-function-for-from-be-bytes/59629/5

**Review by aplanas — APPROVED** [review]

**Comment by ansasaki** [comment]
@sarroutbi Have you tested the interoperability of this between a big endian and a little endian machine?

I'm afraid this can break interoperability. The reason of making the endianess fixed is for all machines to encode data in the same way.

Another downside is the addition of a new dependency. It is not available in Fedora for example, which will cause problems on packaging.

**Comment by sarroutbi** [comment]
> @sarroutbi Have you tested the interoperability of this between a big endian and a little endian machine?
> 
> I'm afraid this can break interoperability. The reason of making the endianess fixed is for all machines to encode data in the same way.
> 
> Another downside is the addition of a new dependency. It is not available in Fedora for example, which will cause problems on packaging.

You are right. I did not figure out that scenario. If codification is hard coded intentionally, I guess #283 should be closed with no resolution. I will close this PR. Sorry for confusion

**Comment by ansasaki** [comment]
@sarroutbi Sorry, I didn't mean you should close this, but to test if this would actually work in an interoperability scenario.

We can test it and reopen this if it works. But then we would have to work to introduce the new dependency in Fedora.

If it doesn't work, then we should do what you proposed and close #283 with the reasoning.

**Comment by sarroutbi** [comment]
> @sarroutbi Sorry, I didn't mean you should close this, but to test if this would actually work in an interoperability scenario.
> 
> We can test it and reopen this if it works. But then we would have to work to introduce the new dependency in Fedora.
> 
> If it doesn't work, then we should do what you proposed and close #283 with the reasoning.

No problem. I will reopen it and once tested, will let you know.

**Review by aplanas — COMMENTED** [review]
I think @ansasaki is right and my review was wrong. Now the data sent from a x86-64 and aarch64 will have different de-serialization order

**Comment by sarroutbi** [comment]
I will close this PR, as it has been confirmed that current development status is intentionally done. My suggestion is closing #283, as it can be confusing

**Pull request closed without merging**
