### PR TITLE
CI: Add packit to run end-to-end tests

### PR DESCRIPTION
**Pull request by ansasaki**
Run selected tests from:

https://github.com/RedHat-SP-Security/keylime-tests

Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

### CODE REVIEW

**Comment by kkaarreell** [comment]
> @kkaarreell @lkatalin Hello, I'm trying to enable packit tests here, but apparently I'm missing something as the jobs are stuck. Maybe we need to install the packit service (https://packit.dev/docs/packit-service/).

Yes, we (@mpeters ) had to enable Packit Service for the keylime project. I do not know whether it is being enabled specifically for a repo (keylime/keylime) or for whole project (keylime user). In the first case I guess the same thing has to be done also for the rust repo. Once installed, Packit test should be run already for a PR adding `.packit.yaml` and `fmf` test plan.

**Comment by mpeters** [comment]
packit is configured in our github org for all repos, so not sure if there's anything else we need.

**Comment by mpeters** [comment]
packit-github-screenshot

**Comment by lkatalin** [comment]
It looked still stuck on "In progress -- Submitting the tests" as of a moment ago, so I re-triggered the testing and hopefully it will go through this time.

**Comment by kkaarreell** [comment]
This PR is lacking `. fmf/version` file. Please, add it.

**Review by lkatalin — APPROVED** [review]

**Pull request merged**
