### PR TITLE
Add REST endpoint to receive revocation notifications

### PR DESCRIPTION
**Pull request by ansasaki**
This implements the agent side of the enhancement proposal: https://github.com/keylime/enhancements/blob/master/53_agent_local_revocation.md

Add the `/notifications/revocation` endpoint to the agent which handles revocation notifications delivered by POST requests.
The format of the notification message is the same used for notifications delivered via ZeroMQ.

This also makes ZeroMQ an optional dependency enabled by default. It is possible to compile without `zmq` by passing the `--no-default-features` options to cargo when building:
```
$ cargo build --no-default-features
```
Fixes: #298

### CODE REVIEW

**Review by lkatalin — COMMENTED** [review]
This LGTM! Thanks @ansasaki  for making this change so quickly.

According to the enhancement it seems like the API version should be bumped - would this break communication with the Python components? I can't remember if they specify a specific API version or "at least" a specific version.

Similar point about the config file, there is a change mentioned in the enhancement but that needs to change in the Python repo to actually be used by the agent.

Is there any downside of potentially having both the REST revocation listener and the zeromq revocation service on at the same time? Should we only enable one at a time? I guess since the revocation message has to be signed, it should make no difference as long as the verifier is behaving in a sane way.

**Comment by THS-on** [comment]
> According to the enhancement it seems like the API version should be bumped - would this break communication with the Python components? I can't remember if they specify a specific API version or "at least" a specific version.

The API version should be increased to `2.1`, because it is only an addition to the API. On the Python side the the connection should still work, because currently we have no checks for that in place. The API on the server side should be increased once https://github.com/keylime/keylime/pull/795 is merged.

**Comment by ansasaki** [comment]
> I'll add a commit to bump the API version.

In the end I amended the commit which introduces the new API to bump the version.

**Comment by lkatalin** [comment]
> > I'll add a commit to bump the API version.
> 
> In the end I amended the commit which introduces the new API to bump the version.

@ansasaki Perfect, thanks!

**Review by lkatalin — COMMENTED** [review]
LGTM except small nit / confusing on the first commit's message: "Also fix the comment for the behavior when the revocation_cert from the configuration file is empty." I don't see the comment there, did it end up going in a different commit?

**Comment by ansasaki** [comment]
> LGTM except small nit / confusing on the first commit's message: "Also fix the comment for the behavior when the revocation_cert from the configuration file is empty." I don't see the comment there, did it end up going in a different commit?

Oh, sorry about that, the change was included in a commit (ab7ed3c7aa773f6cf9c3605c79ca475bde117fc3) in #321.

I'll amend the message to remove that part.

**Review by lkatalin — APPROVED** [review]

**Pull request merged**
