### PR TITLE
keylime-agent/src: update API version to 2.1 to consistent with https//github.com/keylime/keylime/blob/master/docs/rest_apis.rst

### LINKED ISSUE #589: Don't support the RESTful API v2.1 in https://github.com/keylime/keylime/blob/master/docs/rest_apis.rst
Currently, the rust-keylime only supports RESTful API v2.0. When using the https://github.com/keylime/keylime/blob/master/docs/rest_apis.rst, it will be an error.

image

### PR DESCRIPTION
**Pull request by hustliyilin**
Fixes #589 

Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>

### CODE REVIEW

**Review by aplanas — CHANGES_REQUESTED** [review]
In the 2.1 changelog I can see that they removed the vmask parameter, but I still can see some references in the quotes_handler.rs test code (and some comments).

The other change seems to affect the verifier, so I am not sure that has an impact here.

@ansasaki do you know if beside the quotes_handlers change, more changes are required?

**Comment by hustliyilin** [comment]
Thanks @aplanas.   Currently, the rust-keylime only supports RESTful API v2.0. When using the https://github.com/keylime/keylime/blob/master/docs/rest_apis.rst, it will be an error like #588 .

image

So we need to update the API version in the rust-keylime agent or add corresponding instructions to the corresponding REST API documentation.  I'm not sure which way is better.

**Comment by THS-on** [comment]
@aplanas yeah the only change for the agent should be that we no longer send the vmask parameter.

**Comment by hustliyilin** [comment]
> @aplanas yeah the only change for the agent should be that we no longer send the vmask parameter.

Thanks @THS-on . @aplanas Could you review this PR again?

**Review by aplanas — APPROVED** [review]

**Review by ansasaki — APPROVED** [review]
LGTM!

**Pull request merged**
