### PR TITLE
Remove duplicate codeowners file

### PR DESCRIPTION
**Pull request by lkatalin**
Signed-off-by: Lily Sturmann <lsturman@redhat.com>

### CODE REVIEW

**Comment by lkatalin** [comment]
Looks like we need to merge #299 first.

**Comment by lkatalin** [comment]
> What's the background for removing the `rust-team`?

A few weeks ago I added a CODEOWNERs file with myself (and Luke) listed for the purpose of being notified when a new PR is opened. I didn't realize there was already a CODEOWNERs file (with `rust-team`) because I was not getting notified about any new PRs. @ashcrow do you have thoughts on what's best?

**Comment by lkatalin** [comment]
> > What's the background for removing the `rust-team`?
> 
> A few weeks ago I added a CODEOWNERs file with myself (and Luke) listed for the purpose of being notified when a new PR is opened. I didn't realize there was already a CODEOWNERs file (with `rust-team`) because I was not getting notified about any new PRs. @ashcrow do you have thoughts on what's best?

Ah, okay, I see where `rust-team` is [defined](https://github.com/orgs/keylime/teams/rust-team) now. I do want to leave that, so I'll update this PR. Not sure how to also have it ping me specifically about PRs, maybe if I just list myself below `rust-team`... I'll look at the documentation again.

**Comment by ashcrow** [comment]
> do you have thoughts on what's best?

I do not :-) The question was more so curiosity.

**Comment by lkatalin** [comment]
I'll see how this works; I removed the duplicate CODEOWNERS file in favor of the one with `rust-team`, but added myself as an extra person. Maybe this will be annoying and I'll have to take it back off, but it's worth a shot.

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
