### PR TITLE
tpm: also parse TPM2TOOLS_TCTI and TEST_TCTI

### PR DESCRIPTION
**Pull request by THS-on**
This aligns envs for TCTI with ruts-tss-esapi and tpm2-tools.

Fixes: #871

### CODE REVIEW

**Comment by ansasaki** [comment]
In my opinion, this is not correct and even confusing. The agent is not related to and does not use `tpm2-tools` in any way. It would be weird that by changing `tpm2-tools` configuration the agent is also affected.

The `TCTI` configuration should be sufficient, and I believe the confusion comes from proper documentation and better error messages.

**Comment by THS-on** [comment]
Kinda agree, this just aligns it more with what was supported by the old agent. This options is still weird regardless, as its the only option that cannot be set via the config/env combintation. Ideally it would be `KEYLIME_AGENT_TCTI` and the default set as an option in the agent.conf. I can change it to that if you want.

**Comment by ansasaki** [comment]
> Kinda agree, this just aligns it more with what was supported by the old agent. This options is still weird regardless, as its the only option that cannot be set via the config/env combintation. Ideally it would be `KEYLIME_AGENT_TCTI` and the default set as an option in the agent.conf. I can change it to that if you want.

I think that making it a configuration option makes a lot of sense. Adding the `tcti` config option, which would result on `KEYLIME_AGENT_TCTI` env var being supported would be the ideal.

Unfortunately, we would have to still support the plain `TCTI` env var for compatibility. But it is no different from some other options we have.

**Comment by THS-on** [comment]
Ok I'll close this PR then and send a new one to add this as an option + override if TCTI env is set.

**Pull request closed without merging**
