### PR TITLE
ci: Check unit test coverage with cargo tarpaulin

### PR DESCRIPTION
**Pull request by ueno**
This might help address #204 by identifying the code not covered by the unit tests.

### CODE REVIEW

**Comment by ueno** [comment]
Seems like the latest cargo tarpaulin requires ASLR to be disabled. I added a seccomp profile for that based on https://github.com/xd009642/tarpaulin/issues/146.

I haven't tested it with GitHub actions but locally with the following:
`podman run --security-opt seccomp=tests/seccomp-profile.json -v $(pwd):/tmp/code_under_test:Z,rw -w /tmp/code_under_test testimage dbus-run-session -- /tmp/code_under_test/tests/run.sh`

**Comment by lkatalin** [comment]
> Seems like the latest cargo tarpaulin requires ASLR to be disabled. I added a seccomp profile for that based on [xd009642/tarpaulin#146](https://github.com/xd009642/tarpaulin/issues/146).
> 
> I haven't tested it with GitHub actions but locally with the following:
> `podman run --security-opt seccomp=tests/seccomp-profile.json -v $(pwd):/tmp/code_under_test:Z,rw -w /tmp/code_under_test testimage dbus-run-session -- /tmp/code_under_test/tests/run.sh`

@ueno I've installed `cargo tarpaulin` locally and checked out your branch... should I be in a specific directory when I run the command above? I'm not familiar with `cargo tarpaulin` so am trying to do a check this way to see if it works.

**Comment by lkatalin** [comment]
I did run just plain `cargo tarpaulin -v` in my own main branch and that worked nicely to show that we only have something like 33% code coverage.

**Comment by ueno** [comment]
@lkatalin the podman command line should work if you run from the top level directory.

**Comment by lkatalin** [comment]
@ueno What is the "testimage"? Is that a literal image that exists for testing, or should I be changing it to some image of my choice? I'm getting errors that it's not found in any of the registries podman is checking (Fedora, Red Hat, CentOS, etc.):

```
[lily@localhost rust-keylime]$ sudo podman run --security-opt seccomp=tests/seccomp-profile.json -v $(pwd):/tmp/code_under_test:Z,rw -w /tmp/code_under_test testimage dbus-run-session -- /tmp/code_under_test/tests/run.sh
Completed short name "testimage" with unqualified-search registries (origin: /etc/containers/registries.conf)
Trying to pull registry.fedoraproject.org/testimage:latest...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/testimage:latest...
  name unknown: Repo not found
Trying to pull registry.centos.org/testimage:latest...
  manifest unknown: manifest unknown
Trying to pull docker.io/library/testimage:latest...
  denied: requested access to the resource is denied
Error: 4 errors occurred while pulling:
 * Error initializing source docker://registry.fedoraproject.org/testimage:latest: Error reading manifest latest in registry.fedoraproject.org/testimage: manifest unknown: manifest unknown
 * Error initializing source docker://registry.access.redhat.com/testimage:latest: Error reading manifest latest in registry.access.redhat.com/testimage: name unknown: Repo not found
 * Error initializing source docker://registry.centos.org/testimage:latest: Error reading manifest latest in registry.centos.org/testimage: manifest unknown: manifest unknown
 * Error initializing source docker://testimage:latest: Error reading manifest latest in docker.io/library/testimage: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

Pretty sure this is something wrong on my side, but if you know why this is happening that would be helpful.

**Comment by ueno** [comment]
Ah, sorry; the `testimage` container needs to be built first, with `podman build -t testimage tests/`. As it is a one-time operation, I forgot to mention it.

**Comment by lkatalin** [comment]
> Ah, sorry; the `testimage` container needs to be built first, with `podman build -t testimage tests/`. As it is a one-time operation, I forgot to mention it.

Thanks @ueno , that makes sense. I am able to run it now, but have a `spurious network error` with both this and the old command without the seccomp profile, which is just some local problem and not relevant. I am not sure how else to test it. The changes look okay to me from reading them. Should we just try to merge this and update or revert it if there is a problem? @lukehinds ?

**Comment by lukehinds** [comment]
> > Ah, sorry; the `testimage` container needs to be built first, with `podman build -t testimage tests/`. As it is a one-time operation, I forgot to mention it.
> 
> Thanks @ueno , that makes sense. I am able to run it now, but have a `spurious network error` with both this and the old command without the seccomp profile, which is just some local problem and not relevant. I am not sure how else to test it. The changes look okay to me from reading them. Should we just try to merge this and update or revert it if there is a problem? @lukehinds ?

Sorry, just caught this. I am ok with that. @ueno are you ok to rebase?

**Comment by ueno** [comment]
Sure, rebased.

**Review by ashcrow — APPROVED** [review]

**Pull request merged**
