### PR TITLE
Refactor Handlers out of Main

### PR DESCRIPTION
**Pull request by lukehinds**
Main is way to heavy and crowded. Let's start to move some of the
code over into their own mods.

This change moves out the handlers. It also removes a lot of unused imports.

I also removed the sea of commented code out, if we need it, its
in gits history to grab at a later juncture.

### CODE REVIEW

**Comment by lukehinds** [comment]
`Error writing files: failed to resolve mod `handlers`: cannot parse /home/runner/work/rust-keylime/rust-keylime/src/handlers.rs`

Anyone know what cargo fmt is rambling about?

**Comment by ashcrow** [comment]
:+1: to the idea and work. CI is failing with:

```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 78`, unstable features are only available in nightly channel.
Warning: can't set `normalize_comments = false`, unstable features are only available in nightly channel.
Error writing files: failed to resolve mod `handlers`: cannot parse /home/runner/work/rust-keylime/rust-keylime/src/handlers.rs
```

**Comment by ashcrow** [comment]
> Anyone know what cargo fmt is rambling about?

These come up:

- https://github.com/rust-lang/rustfmt/issues/4431
- https://github.com/rust-lang/rustfmt/issues/3901

**Comment by lukehinds** [comment]
> > Anyone know what cargo fmt is rambling about?
> 
> These come up:
> 
>     * [rust-lang/rustfmt#4431](https://github.com/rust-lang/rustfmt/issues/4431)
> 
>     * [rust-lang/rustfmt#3901](https://github.com/rust-lang/rustfmt/issues/3901)

I found the same when I googled around, I am still unsure. It builds fine and if I add a whitespace somewhere fmt tells me what to fix. After fixing all the fmt recommendations it comes up with the statement about not being able to parse.

**Comment by ashcrow** [comment]
From what I gather it's a `rustfmt` bug.

**Review by ashcrow — APPROVED** [review]

**Pull request merged**
