### PR TITLE
Make the API configuration modular

### PR DESCRIPTION
**Pull request by ansasaki**
Move the configuration of the API for each scope into the respective handler file.
Also, move the API configuration into a dedicated file, and make it modular.

This is a preparation to add support for multiple API versions.

### CODE REVIEW

**Review by THS-on — COMMENTED** [review]
Generally LGTM, just would like to have someone else that has more experince with actix to also take a look at it.

**Review by aplanas — APPROVED** [review]
LGTM

**Review by sergio-correia — APPROVED** [review]
This looks good to me as well, thanks.

**Pull request merged**
